/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    tours: Tour;
    departures: Departure;
    'heritage-sites': HeritageSite;
    destinations: Destination;
    experiences: Experience;
    posts: Post;
    categories: Category;
    faqs: Faq;
    inquiries: Inquiry;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    tours: ToursSelect<false> | ToursSelect<true>;
    departures: DeparturesSelect<false> | DeparturesSelect<true>;
    'heritage-sites': HeritageSitesSelect<false> | HeritageSitesSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr' | 'he') | ('en' | 'fr' | 'he')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: 'en' | 'fr' | 'he';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Built from blocks. Marketing landing pages are created here — no developer needed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Use "home" for the homepage. Otherwise this becomes the URL.
   */
  slug: string;
  layout?:
    | (
        | {
            eyebrow?: string | null;
            heading: string;
            subheading?: string | null;
            image?: (number | null) | Media;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image?: (number | null) | Media;
            imagePosition?: ('start' | 'end') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            /**
             * Leave empty to show the most recently published tours.
             */
            tours?: (number | Tour)[] | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tourGrid';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            sites?: (number | HeritageSite)[] | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heritageGrid';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            destinations?: (number | Destination)[] | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'destinationGrid';
          }
        | {
            heading?: string | null;
            scope?: ('general' | 'booking') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqAccordion';
          }
        | {
            heading: string;
            body?: string | null;
            showInquiryButton?: boolean | null;
            showWhatsAppButton?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBanner';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'inquiryForm';
          }
      )[]
    | null;
  /**
   * Around 60 characters. Falls back to the title if left blank.
   */
  metaTitle?: string | null;
  /**
   * Around 155 characters. Falls back to the short description if left blank.
   */
  metaDescription?: string | null;
  /**
   * Image shown when the page is shared. Falls back to the hero image.
   */
  ogImage?: (number | null) | Media;
  /**
   * Hide this page from search engines.
   */
  noindex?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search engines. Required — no image ships without it.
   */
  alt: string;
  caption?: string | null;
  /**
   * Photographer or source, where attribution is required.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours".
 */
export interface Tour {
  id: number;
  title: string;
  /**
   * The URL. Leave blank to generate it from the title.
   */
  slug: string;
  /**
   * One or two sentences, used on cards and in search results.
   */
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  tourType?: ('private' | 'small-group' | 'custom') | null;
  durationDays?: number | null;
  durationNights?: number | null;
  startLocation?: string | null;
  endLocation?: string | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  itinerary?:
    | {
        dayNumber: number;
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        overnightIn?: string | null;
        meals?: ('breakfast' | 'lunch' | 'dinner')[] | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  included?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  excluded?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  accommodationInfo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  transportationInfo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Off by default. While off, the page shows a "Request a quote" call to action instead of a price — so an unpriced tour never renders an empty or invented figure.
   */
  showPrice?: boolean | null;
  priceFrom?: number | null;
  currency?: ('USD' | 'EUR' | 'GBP' | 'MAD') | null;
  priceNote?: string | null;
  availabilityStatus?: ('available' | 'limited' | 'seasonal' | 'on-request' | 'sold-out') | null;
  /**
   * Shown when the tour only runs at certain times of year, so the site never implies year-round availability.
   */
  seasonalNote?: string | null;
  /**
   * Around 60 characters. Falls back to the title if left blank.
   */
  metaTitle?: string | null;
  /**
   * Around 155 characters. Falls back to the short description if left blank.
   */
  metaDescription?: string | null;
  /**
   * Image shown when the page is shared. Falls back to the hero image.
   */
  ogImage?: (number | null) | Media;
  /**
   * Hide this page from search engines.
   */
  noindex?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heritage-sites".
 */
export interface HeritageSite {
  id: number;
  name: string;
  /**
   * Leave blank to generate from the name.
   */
  slug: string;
  siteType:
    'synagogue' | 'cemetery' | 'rabbinical-tomb' | 'mellah' | 'jewish-quarter' | 'museum' | 'landmark' | 'other';
  destination?: (number | null) | Destination;
  city?: string | null;
  region?: string | null;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?: (number | Media)[] | null;
  /**
   * Historical background. Record only what can be supported — cite your sources below.
   */
  historicalInfo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Where the history above comes from. Keeping sources here is how the site stays factual.
   */
  historicalSources?:
    | {
        title: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Access, opening times, dress code, photography rules.
   */
  visitingInfo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedTours?: (number | Tour)[] | null;
  relatedSites?: (number | HeritageSite)[] | null;
  /**
   * Around 60 characters. Falls back to the title if left blank.
   */
  metaTitle?: string | null;
  /**
   * Around 155 characters. Falls back to the short description if left blank.
   */
  metaDescription?: string | null;
  /**
   * Image shown when the page is shared. Falls back to the hero image.
   */
  ogImage?: (number | null) | Media;
  /**
   * Hide this page from search engines.
   */
  noindex?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: number;
  name: string;
  slug: string;
  heroImage?: (number | null) | Media;
  shortDescription?: string | null;
  overview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * This destination's Jewish heritage and community history.
   */
  jewishHeritage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  historicalSignificance?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?: (number | Media)[] | null;
  /**
   * Around 60 characters. Falls back to the title if left blank.
   */
  metaTitle?: string | null;
  /**
   * Around 155 characters. Falls back to the short description if left blank.
   */
  metaDescription?: string | null;
  /**
   * Image shown when the page is shared. Falls back to the hero image.
   */
  ogImage?: (number | null) | Media;
  /**
   * Hide this page from search engines.
   */
  noindex?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Dated departures. A tour with no departures listed is shown as available on request, never as running year-round.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departures".
 */
export interface Departure {
  id: number;
  tour: number | Tour;
  startDate: string;
  endDate?: string | null;
  status: 'open' | 'limited' | 'closed' | 'cancelled';
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  destinations?: (number | Destination)[] | null;
  relatedTours?: (number | Tour)[] | null;
  seo?: {
    /**
     * Around 60 characters. Falls back to the title if left blank.
     */
    metaTitle?: string | null;
    /**
     * Around 155 characters. Falls back to the short description if left blank.
     */
    metaDescription?: string | null;
    /**
     * Image shown when the page is shared. Falls back to the hero image.
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  featuredImage?: (number | null) | Media;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: (number | null) | Category;
  author?: (number | null) | User;
  publishedAt?: string | null;
  relatedTours?: (number | Tour)[] | null;
  relatedSites?: (number | HeritageSite)[] | null;
  /**
   * Around 60 characters. Falls back to the title if left blank.
   */
  metaTitle?: string | null;
  /**
   * Around 155 characters. Falls back to the short description if left blank.
   */
  metaDescription?: string | null;
  /**
   * Image shown when the page is shared. Falls back to the hero image.
   */
  ogImage?: (number | null) | Media;
  /**
   * Hide this page from search engines.
   */
  noindex?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Controls what this person can see and do in the CMS.
   */
  role: 'super-admin' | 'client-admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  scope: 'general' | 'booking' | 'tour' | 'destination';
  tour?: (number | null) | Tour;
  destination?: (number | null) | Destination;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  status: 'new' | 'contacted' | 'qualified' | 'quoted' | 'booked' | 'lost';
  assignedTo?: (number | null) | User;
  fullName: string;
  email: string;
  country?: string | null;
  phone?: string | null;
  preferredDates?: string | null;
  travellers?: number | null;
  tripDuration?: string | null;
  tourInterest?: (number | null) | Tour;
  tripStyle?: ('private' | 'group' | 'either') | null;
  interests?:
    ('synagogues' | 'cemeteries' | 'rabbinical-tombs' | 'mellahs' | 'family-roots' | 'culture' | 'general')[] | null;
  message?: string | null;
  sourcePage?: string | null;
  referrer?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  utmTerm?: string | null;
  utmContent?: string | null;
  internalNotes?:
    | {
        note: string;
        author?: (number | null) | User;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'tours';
        value: number | Tour;
      } | null)
    | ({
        relationTo: 'departures';
        value: number | Departure;
      } | null)
    | ({
        relationTo: 'heritage-sites';
        value: number | HeritageSite;
      } | null)
    | ({
        relationTo: 'destinations';
        value: number | Destination;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              image?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              heading?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              heading?: T;
              content?: T;
              image?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        tourGrid?:
          | T
          | {
              heading?: T;
              intro?: T;
              tours?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        heritageGrid?:
          | T
          | {
              heading?: T;
              intro?: T;
              sites?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        destinationGrid?:
          | T
          | {
              heading?: T;
              intro?: T;
              destinations?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        faqAccordion?:
          | T
          | {
              heading?: T;
              scope?: T;
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              heading?: T;
              body?: T;
              showInquiryButton?: T;
              showWhatsAppButton?: T;
              id?: T;
              blockName?: T;
            };
        inquiryForm?:
          | T
          | {
              heading?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noindex?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours_select".
 */
export interface ToursSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  heroImage?: T;
  gallery?: T;
  tourType?: T;
  durationDays?: T;
  durationNights?: T;
  startLocation?: T;
  endLocation?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  itinerary?:
    | T
    | {
        dayNumber?: T;
        title?: T;
        description?: T;
        overnightIn?: T;
        meals?: T;
        image?: T;
        id?: T;
      };
  included?:
    | T
    | {
        text?: T;
        id?: T;
      };
  excluded?:
    | T
    | {
        text?: T;
        id?: T;
      };
  accommodationInfo?: T;
  transportationInfo?: T;
  showPrice?: T;
  priceFrom?: T;
  currency?: T;
  priceNote?: T;
  availabilityStatus?: T;
  seasonalNote?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noindex?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departures_select".
 */
export interface DeparturesSelect<T extends boolean = true> {
  tour?: T;
  startDate?: T;
  endDate?: T;
  status?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heritage-sites_select".
 */
export interface HeritageSitesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  siteType?: T;
  destination?: T;
  city?: T;
  region?: T;
  shortDescription?: T;
  description?: T;
  images?: T;
  historicalInfo?: T;
  historicalSources?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  visitingInfo?: T;
  relatedTours?: T;
  relatedSites?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noindex?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  heroImage?: T;
  shortDescription?: T;
  overview?: T;
  jewishHeritage?: T;
  historicalSignificance?: T;
  gallery?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noindex?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  image?: T;
  destinations?: T;
  relatedTours?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  relatedTours?: T;
  relatedSites?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noindex?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  scope?: T;
  tour?: T;
  destination?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  status?: T;
  assignedTo?: T;
  fullName?: T;
  email?: T;
  country?: T;
  phone?: T;
  preferredDates?: T;
  travellers?: T;
  tripDuration?: T;
  tourInterest?: T;
  tripStyle?: T;
  interests?: T;
  message?: T;
  sourcePage?: T;
  referrer?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  utmTerm?: T;
  utmContent?: T;
  internalNotes?:
    | T
    | {
        note?: T;
        author?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName?: string | null;
  logo?: (number | null) | Media;
  tagline?: string | null;
  address?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * International format, digits only, no + or spaces. Example: 212600000000. Changing it here updates every WhatsApp button on the site — no redeploy needed.
   */
  whatsappNumber?: string | null;
  /**
   * Pre-filled text. On a tour page the tour name is appended automatically.
   */
  whatsappMessage?: string | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  /**
   * Google Tag Manager container ID, e.g. GTM-XXXXXXX.
   */
  gtmContainerId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header?:
    | {
        label: string;
        /**
         * A path such as /tours, or a full URL.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  footer?:
    | {
        title?: string | null;
        links?:
          | {
              label: string;
              /**
               * A path such as /tours, or a full URL.
               */
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  logo?: T;
  tagline?: T;
  address?: T;
  email?: T;
  phone?: T;
  whatsappNumber?: T;
  whatsappMessage?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  gtmContainerId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}